// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpfcfqedsguugyeahyxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwZmNmcWVkc2d1dWd5ZWFoeXhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4ODAyNTMsImV4cCI6MjA2MDQ1NjI1M30.mN79Cl38WDc0HcjsvKGxD8BAlnyzkSLp98eT_HnByDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);